# Generated by Django 6.0 on 2025-12-18 23:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Jersey number (0-99). Not required to be unique.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('O', 'Offence'), ('D', 'Defence'), ('B', 'Both'), ('G', 'Goalie')], max_length=1)),
                ('external_id', models.CharField(blank=True, help_text='Unique ID from your source data (recommended for imports).', max_length=100, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'id'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='web_player_last_na_28b685_idx'), models.Index(fields=['position'], name='web_player_positio_7922f9_idx'), models.Index(fields=['external_id'], name='web_player_externa_e0bd59_idx')],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField(help_text='e.g., 2026')),
                ('week_number', models.PositiveSmallIntegerField(help_text='1..N within a season')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-season', 'week_number'],
                'indexes': [models.Index(fields=['season', 'week_number'], name='web_week_season_ee7e10_idx'), models.Index(fields=['start_date', 'end_date'], name='web_week_start_d_cd3eee_idx')],
                'constraints': [models.UniqueConstraint(fields=('season', 'week_number'), name='uniq_week_per_season')],
            },
        ),
        migrations.CreateModel(
            name='PlayerWeekStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('penalty_minutes', models.PositiveSmallIntegerField(default=0)),
                ('powerplay_goals', models.PositiveSmallIntegerField(default=0)),
                ('powerplay_assists', models.PositiveSmallIntegerField(default=0)),
                ('shorthanded_goals', models.PositiveSmallIntegerField(default=0)),
                ('loose_balls', models.PositiveSmallIntegerField(default=0)),
                ('turnovers', models.PositiveSmallIntegerField(default=0)),
                ('caused_turnovers', models.PositiveSmallIntegerField(default=0)),
                ('blocked_shots', models.PositiveSmallIntegerField(default=0)),
                ('shots_on_goal', models.PositiveSmallIntegerField(default=0)),
                ('faceoff_percentage', models.DecimalField(decimal_places=2, default=0, help_text='0.00 to 100.00', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_stats', to='web.player')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='web.week')),
            ],
            options={
                'ordering': ['week__season', 'week__week_number', 'player__last_name'],
                'indexes': [models.Index(fields=['week', 'player'], name='web_playerw_week_id_a51ca7_idx'), models.Index(fields=['player', 'week'], name='web_playerw_player__d9668e_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'week'), name='uniq_player_week_stat')],
            },
        ),
    ]
