# Generated by Django 6.0 on 2025-12-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_add_player_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('F', 'Forward'), ('D', 'Defence'), ('T', 'Transition'), ('G', 'Goalie')], max_length=1),
        ),
    ]
