# Generated by Django 6.0 on 2025-12-30 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_add_team_and_player_team'),
        ('web', '0004_alter_player_position'),
    ]

    operations = [
    ]
