# Generated by Django 6.0 on 2026-01-05 01:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_merge_0010_conflicts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='importrun',
            name='team',
        ),
        # Skip AddField for 'team' since it already exists from earlier migrations (0010_ensure_player_team_column_sql)
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Jersey number (0-99). Not required to be unique.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('O', 'Offence'), ('D', 'Defence'), ('T', 'Transition'), ('G', 'Goalie')], max_length=1),
        ),
    ]
