# Generated by Django 6.0 on 2026-01-05 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_player_assigned_side'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyTeamOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.OneToOneField(help_text='The fantasy team this user owns', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='web.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['team__name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('CHAT', 'Chat Message'), ('ADD', 'Player Added'), ('DROP', 'Player Dropped'), ('TRADE', 'Trade'), ('SYSTEM', 'System Notification')], default='CHAT', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, help_text='Player involved in add/drop/trade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='web.player')),
                ('sender', models.ForeignKey(blank=True, help_text='User who sent the message (null for system messages)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Team involved in transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='web.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='web_chatmes_created_d82c52_idx'), models.Index(fields=['message_type'], name='web_chatmes_message_8a6147_idx')],
            },
        ),
    ]
