# Generated by Django 6.0 on 2026-01-05 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_player_team_alter_fantasyteamowner_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='league',
            field=models.ForeignKey(blank=True, help_text='The league this message belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='web.league'),
        ),
    ]
