# Generated by Django 6.0 on 2026-01-05 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_chatmessage_league_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(help_text='The league this roster assignment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='web.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='web.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='web.team')),
            ],
            options={
                'ordering': ['team', 'player'],
                'indexes': [models.Index(fields=['team', 'league'], name='web_roster_team_id_e48ca4_idx'), models.Index(fields=['player', 'league'], name='web_roster_player__67f092_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'league'), name='unique_player_per_league')],
            },
        ),
    ]
