# Generated by Django 6.0 on 2026-01-05 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_player_team_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerweekstat',
            name='goals_against',
            field=models.PositiveSmallIntegerField(default=0, help_text='Goals allowed by goalie'),
        ),
        migrations.AddField(
            model_name='playerweekstat',
            name='saves',
            field=models.PositiveSmallIntegerField(default=0, help_text='Goalie saves'),
        ),
        migrations.AddField(
            model_name='playerweekstat',
            name='wins',
            field=models.PositiveSmallIntegerField(default=0, help_text='Goalie wins'),
        ),
    ]
