# Generated by Django 6.0 on 2026-01-06 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_player_team_playerweekstat_goals_against_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerweekstat',
            name='games_played',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of games played this week'),
        ),
    ]
