# Generated by Django 6.0 on 2026-01-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_player_team_playerweekstat_games_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerweekstat',
            name='faceoff_percentage',
        ),
        migrations.RemoveField(
            model_name='playerweekstat',
            name='penalty_minutes',
        ),
        migrations.RemoveField(
            model_name='playerweekstat',
            name='powerplay_assists',
        ),
        migrations.RemoveField(
            model_name='playerweekstat',
            name='powerplay_goals',
        ),
        migrations.RemoveField(
            model_name='playerweekstat',
            name='shorthanded_goals',
        ),
        migrations.RemoveField(
            model_name='playerweekstat',
            name='shots_on_goal',
        ),
        migrations.RemoveField(
            model_name='playerweekstat',
            name='source_file',
        ),
    ]
