# Generated by Django 6.0 on 2026-01-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_remove_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nll_team',
            field=models.CharField(blank=True, help_text='The actual NLL team this player plays for', max_length=50, null=True),
        ),
    ]
