# Generated by Django 6.0 on 2026-01-07 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_player_nll_team'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roster',
            name='unique_player_per_league',
        ),
        migrations.AddField(
            model_name='roster',
            name='week_added',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Week number when this player was added to the roster', null=True),
        ),
        migrations.AddField(
            model_name='roster',
            name='week_dropped',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Week number when this player was dropped from the roster (NULL if still active)', null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='max_teams',
            field=models.PositiveSmallIntegerField(default=12, help_text='Maximum number of teams allowed (must be even: 4, 6, 8, 10, or 12)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddIndex(
            model_name='roster',
            index=models.Index(fields=['week_added', 'week_dropped'], name='web_roster_week_ad_0284be_idx'),
        ),
        migrations.AddConstraint(
            model_name='roster',
            constraint=models.UniqueConstraint(condition=models.Q(('week_dropped__isnull', True)), fields=('player', 'league'), name='unique_player_per_league'),
        ),
    ]
