# Generated by Django 6.0 on 2026-01-08 04:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_remove_roster_unique_player_per_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether the league is publicly visible and joinable'),
        ),
        migrations.AddField(
            model_name='league',
            name='playoff_weeks',
            field=models.PositiveSmallIntegerField(default=2, help_text='Number of playoff weeks (0-4)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='league',
            name='roster_size',
            field=models.PositiveSmallIntegerField(default=12, help_text='Maximum number of players per team', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='league',
            name='scoring_assists',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Points per assist', max_digits=5),
        ),
        migrations.AddField(
            model_name='league',
            name='scoring_blocked_shots',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Points per blocked shot', max_digits=5),
        ),
        migrations.AddField(
            model_name='league',
            name='scoring_caused_turnovers',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Points per caused turnover', max_digits=5),
        ),
        migrations.AddField(
            model_name='league',
            name='scoring_goalie_assists',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Points per goalie assist', max_digits=5),
        ),
        migrations.AddField(
            model_name='league',
            name='scoring_goalie_goals',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='Points per goalie goal', max_digits=5),
        ),
        migrations.AddField(
            model_name='league',
            name='scoring_goalie_goals_against',
            field=models.DecimalField(decimal_places=2, default=-1.0, help_text='Points per goal against (typically negative)', max_digits=5),
        ),
        migrations.AddField(
            model_name='league',
            name='scoring_goalie_saves',
            field=models.DecimalField(decimal_places=2, default=0.75, help_text='Points per save', max_digits=5),
        ),
        migrations.AddField(
            model_name='league',
            name='scoring_goalie_wins',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Points per goalie win', max_digits=5),
        ),
        migrations.AddField(
            model_name='league',
            name='scoring_goals',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='Points per goal', max_digits=5),
        ),
        migrations.AddField(
            model_name='league',
            name='scoring_loose_balls',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Points per loose ball', max_digits=5),
        ),
        migrations.AddField(
            model_name='league',
            name='scoring_turnovers',
            field=models.DecimalField(decimal_places=2, default=-1.0, help_text='Points per turnover (typically negative)', max_digits=5),
        ),
    ]
