# Generated by Django 6.0 on 2026-01-08 04:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_league_is_public_league_playoff_weeks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='playoff_teams',
            field=models.PositiveSmallIntegerField(default=4, help_text='Number of teams that make playoffs (2, 4, 6, or 8)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
