# Generated by Django 6.0 on 2026-01-09 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_league_playoff_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='use_waivers',
            field=models.BooleanField(default=False, help_text='Enable waiver claims that process when rosters unlock on Tuesday'),
        ),
        migrations.CreateModel(
            name='WaiverClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0, help_text='Waiver priority (lower is better, based on standings)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When this claim was processed', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Why the claim failed (if applicable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(help_text='The league this claim belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='waiver_claims', to='web.league')),
                ('player_to_add', models.ForeignKey(help_text='Player to add if claim is successful', on_delete=django.db.models.deletion.CASCADE, related_name='waiver_claims_for', to='web.player')),
                ('player_to_drop', models.ForeignKey(blank=True, help_text='Player to drop if claim is successful (null if roster has space)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiver_claims_dropping', to='web.player')),
                ('team', models.ForeignKey(help_text='Team making the claim', on_delete=django.db.models.deletion.CASCADE, related_name='waiver_claims', to='web.team')),
                ('week', models.ForeignKey(help_text='Week when this claim was submitted', on_delete=django.db.models.deletion.CASCADE, related_name='waiver_claims', to='web.week')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
                'indexes': [models.Index(fields=['league', 'status', 'priority'], name='web_waiverc_league__db3e59_idx'), models.Index(fields=['week', 'status'], name='web_waiverc_week_id_a5b3a8_idx')],
            },
        ),
    ]
