# Generated by Django 6.0 on 2026-01-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_league_use_waivers_waiverclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='waiver_priority',
            field=models.PositiveIntegerField(default=0, help_text='Lower number = higher priority. Resets to last when claim succeeds'),
        ),
        migrations.AlterField(
            model_name='waiverclaim',
            name='priority',
            field=models.IntegerField(default=0, help_text='Waiver priority snapshot at time of claim (lower is better)'),
        ),
    ]
