# Generated by Django 6.0 on 2026-01-09 03:02

from django.db import migrations, models
import secrets
import string


def generate_unique_ids(apps, schema_editor):
    """Generate unique IDs for existing leagues"""
    League = apps.get_model('web', 'League')
    chars = string.ascii_uppercase + string.digits
    used_codes = set()
    
    for league in League.objects.all():
        while True:
            code = ''.join(secrets.choice(chars) for _ in range(8))
            if code not in used_codes:
                league.unique_id = code
                league.save()
                used_codes.add(code)
                break


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_team_waiver_priority_alter_waiverclaim_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='unique_id',
            field=models.CharField(
                max_length=8,
                null=True,
                blank=True,
                help_text="Unique 8-character code for finding and joining the league"
            ),
        ),
        migrations.RunPython(generate_unique_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='league',
            name='unique_id',
            field=models.CharField(
                max_length=8,
                unique=True,
                editable=False,
                help_text="Unique 8-character code for finding and joining the league"
            ),
        ),
    ]
