# Generated by Django 6.0 on 2026-01-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20260108_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='is_playoff',
            field=models.BooleanField(default=False, help_text='True if this week contains NLL playoff games (not fantasy playoffs)'),
        ),
    ]
