# Generated by Django 6.0 on 2026-01-10 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_week_is_playoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Whether the draft is currently in progress')),
                ('completed', models.BooleanField(default=False, help_text='Whether the draft has been completed')),
                ('draft_order_type', models.CharField(choices=[('RANDOM', 'Random'), ('MANUAL', 'Commissioner Selected')], default='RANDOM', help_text='How the draft order was determined', max_length=10)),
                ('current_round', models.PositiveSmallIntegerField(default=1, help_text='Current round number')),
                ('current_pick', models.PositiveSmallIntegerField(default=1, help_text='Current pick number within the round')),
                ('total_rounds', models.PositiveSmallIntegerField(default=12, help_text='Total number of rounds (should match league roster_size)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('league', models.OneToOneField(help_text='The league this draft belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='web.league')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField(help_text='Round number')),
                ('pick_number', models.PositiveSmallIntegerField(help_text='Pick number within the round')),
                ('overall_pick', models.PositiveSmallIntegerField(help_text='Overall pick number in the draft')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='web.draft')),
                ('player', models.ForeignKey(blank=True, help_text='Player selected (null if not yet picked)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='web.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='web.team')),
            ],
            options={
                'ordering': ['draft', 'overall_pick'],
                'indexes': [models.Index(fields=['draft', 'overall_pick'], name='web_draftpi_draft_i_b7e87a_idx'), models.Index(fields=['team', 'draft'], name='web_draftpi_team_id_557aa5_idx')],
                'unique_together': {('draft', 'round', 'pick_number')},
            },
        ),
        migrations.CreateModel(
            name='DraftPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='Draft position (1 = first pick)')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_positions', to='web.draft')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_positions', to='web.team')),
            ],
            options={
                'ordering': ['draft', 'position'],
                'unique_together': {('draft', 'position'), ('draft', 'team')},
            },
        ),
    ]
