# Generated by Django. Add the new multigame_scoring field to League.
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("web", "0030_week_is_playoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="multigame_scoring",
            field=models.CharField(
                max_length=10,
                choices=[
                    ("highest", "Use highest single-game score (default)"),
                    ("average", "Use average of all games that week"),
                ],
                default="highest",
                help_text="If a player plays multiple games in a week, use their highest single-game score or the average of their games.",
            ),
        ),
    ]
