# Generated by Django 6.0 on 2026-01-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_draft_draftpick_draftposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='draft_style',
            field=models.CharField(choices=[('SNAKE', 'Snake Draft (1,2,3,4 then 4,3,2,1)'), ('LINEAR', 'Linear Draft (1,2,3,4 every round)')], default='SNAKE', help_text='Draft pick order style', max_length=10),
        ),
    ]
