# Generated by Django 6.0 on 2026-01-11 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_draft_draft_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='web.league')),
                ('proposing_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_trades', to='web.team')),
                ('receiving_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trades', to='web.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.player')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='web.trade')),
            ],
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['league', 'status'], name='web_trade_league__d30361_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['proposing_team', 'status'], name='web_trade_proposi_789601_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['receiving_team', 'status'], name='web_trade_receivi_46fb36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tradeplayer',
            unique_together={('trade', 'player')},
        ),
    ]
