# Generated by Django 6.0 on 2026-01-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_trade_tradeplayer_trade_web_trade_league__d30361_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='executed_at',
            field=models.DateTimeField(blank=True, help_text='When the trade was executed (players actually swapped)', null=True),
        ),
    ]
