# Generated by Django 6.0 on 2026-01-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_trade_executed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='playoff_reseed',
            field=models.CharField(choices=[('fixed', '1 seed plays winner of 3 vs 6'), ('reseed', '1 seed plays lowest remaining seed')], default='fixed', help_text='Semifinal matchup: 1 seed plays winner of 3 vs 6 (fixed) or lowest remaining seed (reseed)', max_length=10),
        ),
    ]
