# Generated by Django 6.0 on 2026-01-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_league_multigame_scoring'),
        ('web', '0035_league_playoff_reseed'),
    ]

    operations = [
    ]
