# Generated by Django 6.0 on 2026-01-11 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_merge_20260111_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('nll_game_id', models.CharField(blank=True, help_text='External NLL game ID if available', max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='web.week')),
            ],
            options={
                'ordering': ['date', 'home_team', 'away_team'],
            },
        ),
        migrations.CreateModel(
            name='PlayerGameStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('loose_balls', models.PositiveSmallIntegerField(default=0)),
                ('turnovers', models.PositiveSmallIntegerField(default=0)),
                ('caused_turnovers', models.PositiveSmallIntegerField(default=0)),
                ('blocked_shots', models.PositiveSmallIntegerField(default=0)),
                ('wins', models.PositiveSmallIntegerField(default=0, help_text='Goalie wins')),
                ('saves', models.PositiveSmallIntegerField(default=0, help_text='Goalie saves')),
                ('goals_against', models.PositiveSmallIntegerField(default=0, help_text='Goals allowed by goalie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='web.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='web.player')),
            ],
            options={
                'ordering': ['game__date', 'player__last_name'],
                'constraints': [models.UniqueConstraint(fields=['player', 'game'], name='uniq_player_game_stat')],
                'indexes': [models.Index(fields=['game', 'player'], name='web_playerga_game_id_76dd9e_idx'), models.Index(fields=['player', 'game'], name='web_playerga_player__0f2f8c_idx')],
            },
        ),
    ]
