# Generated by Django 6.0 on 2026-01-11 22:05

from django.db import migrations


def migrate_stats_forward(apps, schema_editor):
    """Migrate stats from PlayerWeekStat to PlayerGameStat and Game"""
    PlayerWeekStat = apps.get_model('web', 'PlayerWeekStat')
    PlayerGameStat = apps.get_model('web', 'PlayerGameStat')
    Game = apps.get_model('web', 'Game')
    Week = apps.get_model('web', 'Week')
    
    # For each week, create a default game if none exists
    weeks = Week.objects.all()
    for week in weeks:
        # Create or get a default game for this week
        game, created = Game.objects.get_or_create(
            week=week,
            date=week.start_date,
            home_team='Default',
            away_team='Default',
        )
        
        # Migrate all PlayerWeekStat records to PlayerGameStat for this game
        stats = PlayerWeekStat.objects.filter(week=week)
        for stat in stats:
            PlayerGameStat.objects.get_or_create(
                player=stat.player,
                game=game,
                defaults={
                    'goals': stat.goals,
                    'assists': stat.assists,
                    'points': stat.points,
                    'loose_balls': stat.loose_balls,
                    'turnovers': stat.turnovers,
                    'caused_turnovers': stat.caused_turnovers,
                    'blocked_shots': stat.blocked_shots,
                    'wins': stat.wins,
                    'saves': stat.saves,
                    'goals_against': stat.goals_against,
                }
            )


def migrate_stats_backward(apps, schema_editor):
    """Rollback - delete migrated PlayerGameStat records"""
    PlayerGameStat = apps.get_model('web', 'PlayerGameStat')
    PlayerGameStat.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_game_playergamestat'),
    ]

    operations = [
        migrations.RunPython(migrate_stats_forward, migrate_stats_backward),
    ]
