# Generated by Django 6.0 on 2026-01-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_migrate_stats_to_playergamestat'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='playerweekstat',
            name='web_playerw_week_id_a51ca7_idx',
        ),
        migrations.RemoveIndex(
            model_name='playerweekstat',
            name='web_playerw_player__d9668e_idx',
        ),
        migrations.RemoveConstraint(
            model_name='playerweekstat',
            name='uniq_player_week_stat',
        ),
        migrations.RenameIndex(
            model_name='playergamestat',
            new_name='web_playerg_game_id_9f5509_idx',
            old_name='web_playerga_game_id_76dd9e_idx',
        ),
        migrations.RenameIndex(
            model_name='playergamestat',
            new_name='web_playerg_player__79fbf0_idx',
            old_name='web_playerga_player__0f2f8c_idx',
        ),
        migrations.AddField(
            model_name='player',
            name='birthdate',
            field=models.DateField(blank=True, help_text="Player's date of birth", null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='draft_team',
            field=models.CharField(blank=True, help_text='NLL team that drafted the player', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='draft_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year player was drafted into NLL', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.CharField(blank=True, help_text='Height (e.g., \'6\\\'2\\"\')', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='hometown',
            field=models.CharField(blank=True, help_text="Player's hometown", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='shoots',
            field=models.CharField(blank=True, help_text='Handedness (Right/Left) or throws/catches hand', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Weight in pounds', null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='scoring_goalie_wins',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Points per goalie win', max_digits=5),
        ),
        migrations.DeleteModel(
            name='PlayerWeekStat',
        ),
    ]
