# Generated by Django 6.0 on 2026-01-13 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_remove_playerweekstat_web_playerw_week_id_a51ca7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='roster_defense',
            field=models.PositiveSmallIntegerField(default=4, help_text='Number of defense (D) roster spots', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='league',
            name='roster_forwards',
            field=models.PositiveSmallIntegerField(default=6, help_text='Number of forward (O) roster spots', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='league',
            name='roster_goalies',
            field=models.PositiveSmallIntegerField(default=2, help_text='Number of goalie (G) roster spots', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
