# Generated by Django 6.0 on 2026-01-13 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_league_roster_defense_league_roster_forwards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='roster_defense',
            field=models.PositiveSmallIntegerField(default=6, help_text='Number of defense (D) roster spots', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='league',
            name='roster_size',
            field=models.PositiveSmallIntegerField(default=14, help_text='Maximum number of players per team', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
