# Generated by Django 6.0 on 2026-01-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_alter_league_roster_defense_alter_league_roster_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='scoring_goalie_goals',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Points per goalie goal', max_digits=5),
        ),
        migrations.AlterField(
            model_name='league',
            name='scoring_goalie_goals_against',
            field=models.DecimalField(decimal_places=2, default=-1.25, help_text='Points per goal against (typically negative)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='league',
            name='scoring_goalie_saves',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Points per save', max_digits=5),
        ),
        migrations.AlterField(
            model_name='league',
            name='scoring_goalie_wins',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='Points per goalie win', max_digits=5),
        ),
        migrations.AddIndex(
            model_name='week',
            index=models.Index(fields=['season', 'start_date'], name='web_week_season_da9a7c_idx'),
        ),
    ]
