# Generated by Django 6.0 on 2026-01-15 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_alter_league_scoring_goalie_goals_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief summary of the issue', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the bug, steps to reproduce, etc.')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('wontfix', "Won't Fix")], default='new', max_length=15)),
                ('page_url', models.URLField(blank=True, help_text='URL where the bug occurred')),
                ('browser_info', models.CharField(blank=True, help_text='Browser and OS information', max_length=255)),
                ('error_message', models.TextField(blank=True, help_text='Any error messages displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the bug was resolved', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from developers/admins')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='web_bugrepo_status_f1973b_idx'), models.Index(fields=['priority', 'status'], name='web_bugrepo_priorit_eed0b0_idx')],
            },
        ),
    ]
