# Generated by Django 6.0 on 2026-01-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_add_roster_lock_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='roster_lock_time',
            field=models.DateTimeField(blank=True, help_text='When rosters lock (time of first game of the week)', null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='roster_unlock_time',
            field=models.DateTimeField(blank=True, help_text='When rosters unlock (Monday 9am PT)', null=True),
        ),
    ]
