# Generated by Django 6.0 on 2026-01-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_alter_week_roster_lock_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='roster_lock_time',
            field=models.DateTimeField(blank=True, help_text='When rosters PERMANENTLY lock (time of first game - locked forever after this)', null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='roster_unlock_time',
            field=models.DateTimeField(blank=True, help_text='When rosters unlock (Monday 9am PT of same week - only unlocked until first game)', null=True),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['date', 'week'], name='web_game_date_070538_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['nll_game_id'], name='web_game_nll_gam_9615b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(fields=('date', 'home_team', 'away_team'), name='unique_game_per_date'),
        ),
    ]
