# Generated by Django 5.2.10 on 2026-01-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_add_team_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='Reason if trade execution failed'),
        ),
        migrations.AddField(
            model_name='trade',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When the trade was processed (executed or failed)', null=True),
        ),
    ]
