# Generated by Django 5.2.10 on 2026-01-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_trade_failure_reason_trade_processed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='roster_format',
            field=models.CharField(choices=[('bestball', 'Best Ball (no lineup management)'), ('traditional', 'Traditional (starter slots: 3O, 3D, 1G)')], default='bestball', help_text='League format: Best Ball (all players score) or Traditional (only starters score)', max_length=15),
        ),
        migrations.AddField(
            model_name='roster',
            name='slot_assignment',
            field=models.CharField(choices=[('starter_o1', 'Starter Offense 1'), ('starter_o2', 'Starter Offense 2'), ('starter_o3', 'Starter Offense 3'), ('starter_d1', 'Starter Defense 1'), ('starter_d2', 'Starter Defense 2'), ('starter_d3', 'Starter Defense 3'), ('starter_g', 'Starter Goalie'), ('bench', 'Bench')], default='bench', help_text="For traditional leagues: which slot this player is assigned to. For best ball leagues: always 'bench' (not used)", max_length=20),
        ),
    ]
