# Generated by Django 5.2.10 on 2026-02-02 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_add_roster_format_and_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='player_dropped',
            field=models.ForeignKey(blank=True, help_text='Player dropped in a waiver/trade transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropped_transactions', to='web.player'),
        ),
    ]
