# Generated by Django 5.2.10 on 2026-02-02 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_chatmessage_player_dropped'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='current_week',
            field=models.ForeignKey(blank=True, help_text='The default week displayed to users (updated every Monday 9am PT)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues_current', to='web.week'),
        ),
    ]
