# Generated by Django 5.1.15 on 2026-02-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_add_league_current_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_rookie',
            field=models.BooleanField(default=False, help_text='Whether the player is a rookie in the current season'),
        ),
    ]
