# Generated by Django 5.2.10 on 2026-02-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_player_is_rookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='league_type',
            field=models.CharField(choices=[('dynasty', 'Dynasty (players stay on teams between seasons)'), ('redraft', 'Re-Draft (all players removed when league renews)')], default='redraft', help_text='Dynasty leagues preserve rosters when renewed; Re-Draft leagues clear all rosters', max_length=10),
        ),
    ]
