# Generated by Django 5.2.10 on 2026-02-04 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_league_league_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RookieDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.PositiveSmallIntegerField(help_text='Season year for which rookies are being drafted')),
                ('is_active', models.BooleanField(default=False, help_text='Whether the draft is currently in progress')),
                ('completed', models.BooleanField(default=False, help_text='Whether the draft has been completed')),
                ('draft_style', models.CharField(choices=[('snake', 'Snake Draft (1,2,3,4 then 4,3,2,1)'), ('linear', 'Linear Draft (1,2,3,4 every round)')], default='snake', help_text='Draft pick order style', max_length=10)),
                ('current_round', models.PositiveSmallIntegerField(default=1, help_text='Current round number (1-2 for rookie drafts)')),
                ('current_pick', models.PositiveSmallIntegerField(default=1, help_text='Current pick number within the round')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('league', models.ForeignKey(help_text='Dynasty league this rookie draft belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rookie_drafts', to='web.league')),
            ],
            options={
                'ordering': ['-season_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RookieDraftPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField(help_text='Round number (1-2)')),
                ('pick_number', models.PositiveSmallIntegerField(help_text='Pick number within the round')),
                ('overall_pick', models.PositiveSmallIntegerField(help_text='Overall pick number in the draft')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(help_text='Rookie draft this pick belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='web.rookiedraft')),
                ('player', models.ForeignKey(blank=True, help_text='Rookie player selected (null if not yet picked)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rookie_draft_picks', to='web.player')),
                ('team', models.ForeignKey(help_text='Team with this pick', on_delete=django.db.models.deletion.CASCADE, related_name='rookie_draft_picks', to='web.team')),
            ],
            options={
                'ordering': ['draft', 'overall_pick'],
            },
        ),
        migrations.AddIndex(
            model_name='rookiedraft',
            index=models.Index(fields=['league', 'season_year'], name='web_rookied_league__412dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='rookiedraft',
            index=models.Index(fields=['is_active'], name='web_rookied_is_acti_a87f92_idx'),
        ),
        migrations.AddIndex(
            model_name='rookiedraftpick',
            index=models.Index(fields=['draft', 'overall_pick'], name='web_rookied_draft_i_afa6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='rookiedraftpick',
            index=models.Index(fields=['team', 'draft'], name='web_rookied_team_id_b6a6e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rookiedraftpick',
            unique_together={('draft', 'round', 'pick_number')},
        ),
    ]
