# Generated by Django 5.2.10 on 2026-02-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_rookiedraft_rookiedraftpick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rookiedraft',
            name='order_locked',
            field=models.BooleanField(default=False, help_text="Whether draft order is locked (can't modify once locked)"),
        ),
    ]
