# Generated by Django 5.2.10 on 2026-02-04 04:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_rookiedraft_order_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiSquad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveSmallIntegerField(help_text='Which taxi slot (1, 2, or 3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Whether this taxi squad slot is locked (season started)')),
                ('player', models.ForeignKey(help_text='Rookie player in this taxi slot', on_delete=django.db.models.deletion.CASCADE, related_name='taxi_squad_entries', to='web.player')),
                ('team', models.ForeignKey(help_text='Fantasy team this taxi squad belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='taxi_squad', to='web.team')),
            ],
            options={
                'ordering': ['team', 'slot_number'],
                'indexes': [models.Index(fields=['team', 'is_locked'], name='web_taxisqu_team_id_e64689_idx'), models.Index(fields=['player'], name='web_taxisqu_player__8e9c3d_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'slot_number'), name='unique_taxi_slot_per_team'), models.CheckConstraint(condition=models.Q(('slot_number__in', [1, 2, 3])), name='taxi_slot_1_to_3')],
                'unique_together': {('team', 'player')},
            },
        ),
    ]
