# Generated by Django 5.2.10 on 2026-02-04 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0056_taxisquad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxisquad',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Rookie player in this taxi slot (null if empty)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxi_squad_entries', to='web.player'),
        ),
    ]
