# Generated by Django 5.2.10 on 2026-02-04 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0057_alter_taxisquad_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='taxi_squad_size',
            field=models.PositiveSmallIntegerField(default=3, help_text='Number of taxi squad slots for rookies (0-4, only used in Dynasty leagues)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
