# Generated by Django 5.2.10 on 2026-02-05 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0058_league_taxi_squad_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='roster_bench',
            field=models.PositiveSmallIntegerField(default=6, help_text='Number of bench roster spots (for traditional leagues)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
