# Generated by Django 5.2.10 on 2026-02-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0059_league_roster_bench'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='allow_transition_in_goalies',
            field=models.BooleanField(default=False, help_text='Allow Transition (T) players to be placed in Goalie (G) roster slots'),
        ),
    ]
