# Generated by Django 5.1.15 on 2026-02-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0060_league_allow_transition_in_goalies'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='use_taxi_squad',
            field=models.BooleanField(default=True, help_text="Enable taxi squad feature in Dynasty leagues (allows holding rookies who don't score)"),
        ),
    ]
