# Generated by Django 5.1.15 on 2026-02-07 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0061_league_use_taxi_squad'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taxisquad',
            name='taxi_slot_1_to_3',
        ),
        migrations.AlterField(
            model_name='taxisquad',
            name='slot_number',
            field=models.PositiveSmallIntegerField(help_text='Which taxi slot (1, 2, 3, or 4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddConstraint(
            model_name='taxisquad',
            constraint=models.CheckConstraint(condition=models.Q(('slot_number__in', [1, 2, 3, 4])), name='taxi_slot_1_to_3'),
        ),
    ]
