# Generated by Django 5.1.15 on 2026-02-07 19:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0062_remove_taxisquad_taxi_slot_1_to_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='use_future_rookie_picks',
            field=models.BooleanField(default=True, help_text='Enable future rookie picks feature in Dynasty leagues (teams own picks for multiple years)'),
        ),
        migrations.CreateModel(
            name='FutureRookiePick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='Future year this pick is for (e.g., 2026, 2027)')),
                ('round_number', models.PositiveSmallIntegerField(help_text='Round number (1-12, or however many rounds in league)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('pick_number', models.PositiveSmallIntegerField(help_text='Pick order within the round (1 to num_teams)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(help_text='League this pick belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='future_rookie_picks', to='web.league')),
                ('original_owner', models.ForeignKey(help_text='Team that originally owned this pick (used for draft seeding)', on_delete=django.db.models.deletion.CASCADE, related_name='future_picks_original_owner', to='web.team')),
                ('team', models.ForeignKey(help_text='Team that currently owns this pick', on_delete=django.db.models.deletion.CASCADE, related_name='future_rookie_picks', to='web.team')),
            ],
            options={
                'ordering': ['year', 'round_number', 'pick_number'],
            },
        ),
        migrations.CreateModel(
            name='TradePick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_team', models.ForeignKey(help_text='Current owner of the pick', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.team')),
                ('future_rookie_pick', models.ForeignKey(help_text='The future pick being traded', on_delete=django.db.models.deletion.CASCADE, to='web.futurerookiepick')),
                ('trade', models.ForeignKey(help_text='Trade this pick is part of', on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='web.trade')),
            ],
        ),
        migrations.AddIndex(
            model_name='futurerookiepick',
            index=models.Index(fields=['league', 'year'], name='web_futurer_league__5677f2_idx'),
        ),
        migrations.AddIndex(
            model_name='futurerookiepick',
            index=models.Index(fields=['team', 'year'], name='web_futurer_team_id_3f6020_idx'),
        ),
        migrations.AddIndex(
            model_name='futurerookiepick',
            index=models.Index(fields=['original_owner', 'year'], name='web_futurer_origina_0efdf0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='futurerookiepick',
            unique_together={('league', 'year', 'round_number', 'pick_number')},
        ),
        migrations.AlterUniqueTogether(
            name='tradepick',
            unique_together={('trade', 'future_rookie_pick')},
        ),
    ]
