# Generated by Django 5.2.10 on 2026-02-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0063_league_use_future_rookie_picks_futurerookiepick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurerookiepick',
            name='order_finalized',
            field=models.BooleanField(default=False, help_text="Whether the pick order is finalized (only True for next season's draft)"),
        ),
    ]
