# Generated by Django 5.1.15 on 2026-04-14 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0066_add_offseason_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='current_week',
            field=models.ForeignKey(blank=True, help_text='The default week displayed to users (updated every Tuesday 9am PT)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues_current', to='web.week'),
        ),
        migrations.AlterField(
            model_name='week',
            name='roster_unlock_time',
            field=models.DateTimeField(blank=True, help_text='When rosters unlock (Tuesday 9am PT of same week - only unlocked until first game)', null=True),
        ),
        migrations.CreateModel(
            name='NLLTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(help_text='Date the transaction occurred')),
                ('transaction_type', models.CharField(choices=[('signed', 'Signed'), ('traded', 'Traded'), ('released', 'Released'), ('waived', 'Waived'), ('reassigned', 'Reassigned'), ('activated', 'Activated'), ('retired', 'Retired'), ('other', 'Other')], help_text='Type of transaction', max_length=20)),
                ('player_name', models.CharField(help_text='Player name as listed in transaction', max_length=100)),
                ('from_team', models.CharField(blank=True, help_text='Team player left from (for trades/releases)', max_length=50, null=True)),
                ('to_team', models.CharField(blank=True, help_text='Team player went to (for signings/trades)', max_length=50, null=True)),
                ('details', models.TextField(blank=True, help_text='Additional details about the transaction', null=True)),
                ('nll_url', models.URLField(blank=True, help_text='Link to original NLL news article', null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, help_text='Matched player record if available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nll_transactions', to='web.player')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['-transaction_date'], name='web_nlltran_transac_6f4b35_idx'), models.Index(fields=['transaction_type'], name='web_nlltran_transac_4dcbf3_idx'), models.Index(fields=['player_name'], name='web_nlltran_player__082e29_idx')],
            },
        ),
    ]
