# Generated by Django 5.1.15 on 2026-04-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0067_alter_league_current_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlltransaction',
            name='transaction_type',
            field=models.CharField(choices=[('signed', 'Signed'), ('traded', 'Traded'), ('released', 'Released'), ('waived', 'Waived'), ('reassigned', 'Reassigned'), ('injured_reserve', 'Placed on Injured Reserve'), ('activated', 'Activated/Returned'), ('retired', 'Retired'), ('other', 'Other')], help_text='Type of transaction', max_length=20),
        ),
    ]
