# Generated by Django 5.1.15 on 2026-04-14 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0068_alter_nlltransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='allow_ir_slots',
            field=models.BooleanField(default=False, help_text='Enable Injured Reserve roster slots for this league'),
        ),
        migrations.AddField(
            model_name='league',
            name='ir_slots',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of Injured Reserve roster slots (0-5, only applies if allow_ir_slots is enabled)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
