# Generated by Django 5.1.15 on 2026-04-15 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0069_league_allow_ir_slots_league_ir_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.PositiveIntegerField(help_text='Year of the archived season')),
                ('final_standings', models.JSONField(blank=True, default=dict, help_text='JSON snapshot of final standings (team names and scores)')),
                ('archived_at', models.DateTimeField(auto_now_add=True, help_text='When this season was archived')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated')),
            ],
            options={
                'ordering': ['-season_year'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team_name_per_league',
        ),
        migrations.AddField(
            model_name='team',
            name='season_year',
            field=models.PositiveIntegerField(blank=True, help_text='Season year this team belongs to (null for teams created before multi-season support)', null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='season',
            field=models.PositiveIntegerField(default=2026, help_text='Current season year (auto-incremented when league is renewed)'),
        ),
        migrations.AlterField(
            model_name='league',
            name='status',
            field=models.CharField(choices=[('active', 'Season in progress'), ('season_complete', 'Season ended, ready for renewal')], default='active', help_text='Current league status', max_length=20),
        ),
        migrations.AlterField(
            model_name='roster',
            name='slot_assignment',
            field=models.CharField(choices=[('starter_o1', 'Starter Offense 1'), ('starter_o2', 'Starter Offense 2'), ('starter_o3', 'Starter Offense 3'), ('starter_d1', 'Starter Defense 1'), ('starter_d2', 'Starter Defense 2'), ('starter_d3', 'Starter Defense 3'), ('starter_g', 'Starter Goalie'), ('bench', 'Bench'), ('ir', 'Injured Reserve')], default='bench', help_text="For traditional leagues: which slot this player is assigned to. For best ball leagues: always 'bench' (not used)", max_length=20),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name', 'league', 'season_year'), name='unique_team_name_per_league_season'),
        ),
        migrations.AddField(
            model_name='leaguehistory',
            name='champion',
            field=models.ForeignKey(blank=True, help_text='The team that won the championship', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='championships', to='web.team'),
        ),
        migrations.AddField(
            model_name='leaguehistory',
            name='league',
            field=models.ForeignKey(help_text='The league this season history belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='season_archives', to='web.league'),
        ),
        migrations.AddIndex(
            model_name='leaguehistory',
            index=models.Index(fields=['league', '-season_year'], name='web_leagueh_league__b12638_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaguehistory',
            constraint=models.UniqueConstraint(fields=('league', 'season_year'), name='unique_league_season_archive'),
        ),
    ]
